#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
# 
# For more details, review a copy of the GNU General Public License at <https://www.gnu.org/licenses/>.
#
# Created by: Leandro Fernandes Correia
# Linkedin: https://www.linkedin.com/in/leo-correia/
# GitHub: https://github.com/leo-fcorreia
# Website: https://reptsec.com
# Year: 2025
#
# Description:
# This script was developed to enhance the detection of events generated by syslog messages 
# from the IDS (Intrusion Detection Service) of the Cisco ASA Firewall.
#
# Disclaimer:
# I am not responsible for the execution of these scripts, as they serve as a reference 
# for improving detections. I highly recommend reviewing your rules and decoders in a 
# test environment before applying them to production.
#
# References:
# - Wazuh Regex Documentation:
#   https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html
# 
# - Cisco ASA Syslog Messages 4-4000nn:
#   https://www.cisco.com/c/en/us/td/docs/security/asa/syslog/b_syslog/syslog-messages-400000-to-450001.html#con_4772079

echo "Running: python3 update_cisco-asa_ids-decoders.py"
python3 update_cisco-asa_ids-decoders.py
if [ $? -eq 0 ]; then
    echo "Successfully executed: update_cisco-asa_ids-decoders.py"
else
    echo "Error executing: update_cisco-asa_ids-decoders.py"
    exit 1
fi

echo "Running: python3 update_cisco-asa_ids-rules.py"
python3 update_cisco-asa_ids-rules.py
if [ $? -eq 0 ]; then
    echo "Successfully executed: update_cisco-asa_ids-rules.py"
else
    echo "Error executing: update_cisco-asa_ids-rules.py"
    exit 1
fi

echo "Restarting Wazuh Manager..."
systemctl restart wazuh-manager
if [ $? -eq 0 ]; then
    echo "Wazuh Manager restarted successfully."
else
    echo "Error restarting Wazuh Manager."
    exit 1
fi

echo "All updates applied successfully."
